### ISSUE TITLE
df plugin doesn't show device name on fetch

### ISSUE THREAD

**Issue by APz** [opbod/munin-node-sim#2]
The df plugin shows the device names correctly during the config command, but the on fetch it just returns raw usage percentage number without listing to which device it belongs to.

It appears the code to output the values is missing the device name in df's line 53. I tried modifying it like this and now Munin accepts the value:

`values.append("{}.value {}".format(mount_point.replace("/", "_"), value_percent[:-1]))`

**Comment by killerbees19** [comment]
Thanks for your contribution! 🤓

I've created and merged commit 2b0c654d642a2c93da755f69dd1b588a4504a33f with your GitHub username as author.
